STRIPE_PUBLISHABLE_KEY: example
STRIPE_API_SECRET_KEY: example
MAILGUN_USERNAME: example
MAILGUN_PASSWORD: example
BETA_PASSWORD: example
FACEBOOK_APP_ID: example
FACEBOOK_APP_SECRET: example
GOOGLE_CLIENT_ID: example
GOOGLE_CLIENT_SECRET: example
SLACK_WEBHOOK_URL: example
PROD_MICROSERVICE_BASE_URL: example
MICROSERVICE_BASE_URL: example
S3_BUCKET: example
AWS_ACCESS_KEY_ID: example
AWS_SECRET_ACCESS_KEY: example
AWS_S3_REGION: example
